Updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,50 +6,50 @@ on:
       - develop
 
 jobs:
-  # build-push:
-  #   runs-on: ubuntu-latest
+  build-push:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v3
-  #       with:
-  #         driver-opts: network=host
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          driver-opts: network=host
 
-  #     - name: Log in to GitHub Container Registry
-  #       uses: docker/login-action@v2
-  #       with:
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.CONTAINER_REGISTRY_PAT_TOKEN }}
-  #         registry: ghcr.io
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          username: ${{ github.actor }}
+          password: ${{ secrets.CONTAINER_REGISTRY_PAT_TOKEN }}
+          registry: ghcr.io
 
-  #     - name: Build Docker image
-  #       run: |
-  #         docker build -f ./Dockerfile -t ghcr.io/${{ github.repository }}-app:latest . --no-cache
-  #         docker build -f ./Dockerfile.db -t ghcr.io/${{ github.repository }}-migrator:latest . --no-cache
+      - name: Build Docker image
+        run: |
+          docker build -f ./Dockerfile -t ghcr.io/app.${{ github.repository }}/${{ github.ref_name }}:latest . --no-cache
+          docker build -f ./Dockerfile.db -t ghcr.io/migrator.${{ github.repository }}/${{ github.ref_name }}:latest . --no-cache
 
-  #     - name: Push Docker image to GitHub Container Registry
-  #       run: |
-  #         docker push ghcr.io/${{ github.repository }}-app:latest
-  #         docker push ghcr.io/${{ github.repository }}-migrator:latest
+      - name: Push Docker image to GitHub Container Registry
+        run: |
+          docker push ghcr.io/app.${{ github.repository }}/${{ github.ref_name }}:latest
+          docker push ghcr.io/migrator.${{ github.repository }}/${{ github.ref_name }}:latest
 
-  #     - name: Delete older local images
-  #       run: |
-  #         app_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/belsterns/eztest.ai-app" | grep -v ':latest' || true)
-  #         migrator_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/belsterns/eztest.ai-migrator" | grep -v ':latest' || true)
+      - name: Delete older local images
+        run: |
+          app_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/app.${{ github.repository }}/${{ github.ref_name }}" | grep -v ':latest' || true)
+          migrator_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/migrator.${{ github.repository }}/${{ github.ref_name }}" | grep -v ':latest' || true)
           
-  #         if [ -z "$app_images" ] && [ -z "$migrator_images" ]; then
-  #           echo "No old images found to delete."
-  #         else
-  #           for image in $app_images $migrator_images; do
-  #             echo "Removing old image $image"
-  #             docker rmi "$image" || echo "Failed to remove image $image"
-  #           done
-  #         fi
+          if [ -z "$app_images" ] && [ -z "$migrator_images" ]; then
+            echo "No old images found to delete."
+          else
+            for image in $app_images $migrator_images; do
+              echo "Removing old image $image"
+              docker rmi "$image" || echo "Failed to remove image $image"
+            done
+          fi
           
-  #         docker builder prune -f || echo "Failed to prune builder cache"
+          docker builder prune -f || echo "Failed to prune builder cache"
 
 
   pull-deploy:
@@ -78,8 +78,8 @@ jobs:
         run: |
           ssh -o LogLevel=verbose -o StrictHostKeyChecking=no apl_dev@${{ secrets.DEV_SERVER_IP }} << EOF
           docker login --username ${{ github.actor }} --password ${{ secrets.CONTAINER_REGISTRY_PAT_TOKEN }} ghcr.io
-          docker image pull ghcr.io/${{ github.repository }}-app:latest
-          docker image pull ghcr.io/${{ github.repository }}-migrator:latest
+          docker image pull ghcr.io/app.${{ github.repository }}/${{ github.ref_name }}:latest
+          docker image pull ghcr.io/migrator.${{ github.repository }}/${{ github.ref_name }}:latest
           docker compose -f ${DEV_PRJ_PATH}/docker-compose.yml up -d --force-recreate
           docker image prune -f
           EOF
